[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mathobj"
version = "0.0.0"
authors = [{ name = "Luke Oguro" },]
description = "Mathematical objects"
license = { text = "MIT Licence" }
requires-python = ">=3.8.5"
dependencies = [
	"numpy"
] 
